---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bandit
  annotations:
    thoth-station.ninja/template-version: 0.1.0
  labels:
    app: thoth
    component: si-bandit
spec:
  templates:
    - name: bandit-from-dir
      inputs:
        parameters:
          - name: "THOTH_SI_BANDIT_JOB_ID"
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_SI_BANDIT_PACKAGE_NAME"
          - name: "THOTH_SI_BANDIT_PACKAGE_VERSION"
          - name: "THOTH_SI_BANDIT_PACKAGE_INDEX"
          - name: "THOTH_SI_BANDIT_DIR"
      container:
        name: si-bandit
        image: "si-bandit"
        env:
          - name: THOTH_DOCUMENT_ID
            value: "{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: THOTH_SI_BANDIT_OUTPUT
            value: "/mnt/workdir/bandit_results"
          - name: THOTH_SI_BANDIT_PACKAGE_NAME
            value: "{{inputs.parameters.THOTH_SI_BANDIT_PACKAGE_NAME}}"
          - name: THOTH_SI_BANDIT_PACKAGE_VERSION
            value: "{{inputs.parameters.THOTH_SI_BANDIT_PACKAGE_VERSION}}"
          - name: THOTH_SI_BANDIT_PACKAGE_INDEX
            value: "{{inputs.parameters.THOTH_SI_BANDIT_PACKAGE_INDEX}}"
          - name: THOTH_SI_BANDIT_DIR
            value: "{{inputs.parameters.THOTH_SI_BANDIT_DIR}}"
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
